import { cva } from '../../styled-system/css'

export const buttonStyles = cva({
  base: {
    display: 'inline-flex',
    flexShrink: '0',
    flexWrap: 'nowrap',
    alignItems: 'center',
    justifyContent: 'center',
    gap: '0.375rem',
    textAlign: 'center',
    verticalAlign: 'middle',
    cursor: 'pointer',
    userSelect: 'none',
    textDecoration: 'none',
    appearance: 'none',
    '&:is([type="checkbox"], [type="radio"])[aria-label]:after': {
      content: 'attr(aria-label)',
    },
    fontWeight: '600',
    borderRadius: 'var(--radius-field)',
    borderWidth: 'var(--border, 1px)',
    touchAction: 'manipulation',
    transitionProperty: 'color, background-color, border-color, box-shadow, transform',
    transitionTimingFunction: 'cubic-bezier(0, 0, 0.2, 1)',
    transitionDuration: '0.2s',

    '--btn-p': '1rem',
    '--btn-fg': 'var(--colors-base-content)',
    '--btn-bg': 'var(--btn-color, var(--colors-base-200))',
    '--btn-border': 'color-mix(in oklab, var(--btn-color, var(--colors-base-200)), #000 calc(var(--depth, 1) * 5%))',
    '--btn-shadow': [
      '0 3px 2px -2px color-mix(in oklab, var(--btn-bg) calc(var(--depth, 1) * 30%), transparent)',
      '0 4px 3px -2px color-mix(in oklab, var(--btn-bg) calc(var(--depth, 1) * 30%), transparent)',
    ].join(', '),
    '--btn-inset': '0 0.5px 0 0.5px oklch(100% 0 0 / calc(var(--depth, 1) * 6%))',

    height: 'var(--size)',
    paddingInline: 'var(--btn-p)',
    fontSize: 'var(--fontsize, 0.875rem)',
    backgroundColor: 'var(--btn-bg)',
    color: 'var(--btn-fg)',
    borderColor: 'var(--btn-border)',
    borderStyle: 'var(--btn-border-style, solid)',
    outlineColor: 'var(--btn-color, var(--colors-base-content))',
    outlineOffset: '2px',

    backgroundImage: 'none, var(--fx-noise)',
    backgroundSize: 'auto, calc(var(--noise, 0) * 100%)',
    textShadow: '0 0.5px oklch(100% 0 0 / calc(var(--depth, 1) * 0.15))',
    boxShadow: 'var(--btn-inset) inset, var(--btn-shadow)',

    '@media (hover: hover)': {
      _hover: {
        '--btn-bg': 'color-mix(in oklab, var(--btn-color, var(--colors-base-200)), #000 7%)',
        color: 'var(--btn-fg)',
        '--btn-border': 'color-mix(in oklab, var(--btn-bg), #000 calc(var(--depth, 1) * 5%))',
        '--btn-border-style': 'solid',
        '--btn-inset': '0 0.5px 0 0.5px oklch(100% 0 0 / calc(var(--depth, 1) * 6%))',
        '--btn-shadow': [
          '0 3px 2px -2px color-mix(in oklab, var(--btn-bg) calc(var(--depth, 1) * 30%), transparent)',
          '0 4px 3px -2px color-mix(in oklab, var(--btn-bg) calc(var(--depth, 1) * 30%), transparent)',
        ].join(', '),
      },
    },

    '&:active:not([data-active])': {
      translate: '0 0.5px',
      '--btn-bg': 'color-mix(in oklab, var(--btn-color, var(--colors-base-200)), #000 5%)',
      color: 'var(--btn-fg, var(--colors-base-content))',
      '--btn-border': 'color-mix(in oklab, var(--btn-color, var(--colors-base-200)), #000 7%)',
      '--btn-border-style': 'solid',
      '--btn-inset': '0 0 0 0 oklch(0% 0 0 / 0)',
      '--btn-shadow': '0 0 0 0 oklch(0% 0 0 / 0)',
    },

    _focusVisible: {
      outlineWidth: '2px',
      outlineStyle: 'solid',
      isolation: 'isolate',
    },

    '&:disabled, &[disabled], &[aria-disabled="true"], &.btn-disabled': {
      pointerEvents: 'none',
      color: 'color-mix(in oklch, var(--colors-base-content) 20%, transparent)',
      '--btn-bg': 'transparent',
      '--btn-border': 'transparent',
      backgroundImage: 'none',
      '--btn-inset': '0 0 0 0 oklch(0% 0 0 / 0)',
      '--btn-shadow': '0 0 0 0 oklch(0% 0 0 / 0)',
    },
  },
  variants: {
    color: {
      neutral: { '--btn-color': 'var(--colors-neutral)', '--btn-fg': 'var(--colors-neutral-content)' },
      primary: { '--btn-color': 'var(--colors-primary)', '--btn-fg': 'var(--colors-primary-content)' },
      secondary: { '--btn-color': 'var(--colors-secondary)', '--btn-fg': 'var(--colors-secondary-content)' },
      accent: { '--btn-color': 'var(--colors-accent)', '--btn-fg': 'var(--colors-accent-content)' },
      info: { '--btn-color': 'var(--colors-info)', '--btn-fg': 'var(--colors-info-content)' },
      success: { '--btn-color': 'var(--colors-success)', '--btn-fg': 'var(--colors-success-content)' },
      warning: { '--btn-color': 'var(--colors-warning)', '--btn-fg': 'var(--colors-warning-content)' },
      error: { '--btn-color': 'var(--colors-error)', '--btn-fg': 'var(--colors-error-content)' },
    },
    variant: {
      outline: {
        '--btn-bg': 'transparent',
        color: 'var(--btn-color, var(--colors-base-content))',
        '--btn-border': 'var(--btn-color, var(--colors-base-content))',
        '--btn-border-style': 'solid',
        backgroundImage: 'none',
        '--btn-inset': '0 0 0 0 oklch(0% 0 0 / 0)',
        '--btn-shadow': '0 0 0 0 oklch(0% 0 0 / 0)',
      },
      dash: {
        '--btn-bg': 'transparent',
        color: 'var(--btn-color, var(--colors-base-content))',
        '--btn-border': 'var(--btn-color, var(--colors-base-content))',
        '--btn-border-style': 'dashed',
        backgroundImage: 'none',
        '--btn-inset': '0 0 0 0 oklch(0% 0 0 / 0)',
        '--btn-shadow': '0 0 0 0 oklch(0% 0 0 / 0)',
      },
      soft: {
        '--btn-bg': 'color-mix(in oklab, var(--btn-color, var(--colors-base-content)) 8%, var(--colors-base-100))',
        color: 'var(--btn-color, var(--colors-base-content))',
        '--btn-border': 'color-mix(in oklab, var(--btn-color, var(--colors-base-content)) 10%, var(--colors-base-100))',
        '--btn-border-style': 'solid',
        backgroundImage: 'none',
        '--btn-inset': '0 0 0 0 oklch(0% 0 0 / 0)',
        '--btn-shadow': '0 0 0 0 oklch(0% 0 0 / 0)',
      },
      ghost: {
        '--btn-bg': 'transparent',
        color: 'var(--btn-color, currentColor)',
        '--btn-border': 'transparent',
        backgroundImage: 'none',
        '--btn-inset': '0 0 0 0 oklch(0% 0 0 / 0)',
        '--btn-shadow': '0 0 0 0 oklch(0% 0 0 / 0)',
      },
      link: {
        '--btn-bg': 'transparent',
        color: 'var(--btn-color, var(--colors-primary))',
        '--btn-border': 'transparent',
        textDecoration: 'underline',
        backgroundImage: 'none',
        '--btn-inset': '0 0 0 0 oklch(0% 0 0 / 0)',
        '--btn-shadow': '0 0 0 0 oklch(0% 0 0 / 0)',
      },
    },
    size: {
      xs: { '--fontsize': '0.6875rem', '--btn-p': '0.5rem', '--size': '1.5rem' },
      sm: { '--fontsize': '0.75rem', '--btn-p': '0.75rem', '--size': '2rem' },
      md: { '--fontsize': '0.875rem', '--btn-p': '1rem', '--size': '2.5rem' },
      lg: { '--fontsize': '1.125rem', '--btn-p': '1.25rem', '--size': '3rem' },
      xl: { '--fontsize': '1.375rem', '--btn-p': '1.5rem', '--size': '3.5rem' },
    },
    active: {
      true: {
        '--btn-bg': 'color-mix(in oklab, var(--btn-color, var(--colors-base-200)), #000 5%)',
        color: 'var(--btn-fg, var(--colors-base-content))',
        '--btn-border': 'color-mix(in oklab, var(--btn-color, var(--colors-base-200)), #000 7%)',
        '--btn-border-style': 'solid',
        '--btn-inset': '0 0 0 0 oklch(0% 0 0 / 0)',
        '--btn-shadow': '0 0 0 0 oklch(0% 0 0 / 0)',
        isolation: 'isolate',
      },
    },
    shape: {
      square: { paddingInline: '0', width: 'var(--size)', height: 'var(--size)' },
      circle: { paddingInline: '0', width: 'var(--size)', height: 'var(--size)', borderRadius: '9999px' },
    },
    fluid: {
      block: { width: '100%' },
      wide: { width: '100%', maxWidth: '16rem' },
    },
  },
  defaultVariants: {
    size: 'md',
  },
})
