import { cva } from '../../styled-system/css'

export const checkboxStyles = cva({
  base: {
    position: 'relative',
    display: 'inline-block',
    flexShrink: '0',
    verticalAlign: 'middle',
    cursor: 'pointer',
    appearance: 'none',
    color: 'var(--colors-base-content)',
    borderRadius: 'var(--radius-selector)',
    '--input-color': 'color-mix(in oklab, var(--colors-base-content) 20%, transparent)',
    border: 'var(--border, 1px) solid var(--input-color)',
    boxShadow: '0 1px oklch(0% 0 0 / 0.1) inset',
    transition: 'background-color 0.2s, box-shadow 0.2s',
    '--checkbox-size': '1.5rem',
    width: 'var(--checkbox-size)',
    height: 'var(--checkbox-size)',
    padding: '0.25rem',
    _before: {
      content: '""',
      display: 'block',
      width: '100%',
      height: '100%',
      rotate: '45deg',
      backgroundColor: 'currentColor',
      opacity: '0',
      clipPath: 'polygon(20% 100%, 20% 80%, 50% 80%, 50% 80%, 70% 80%, 70% 100%)',
      transition: 'clip-path 0.3s, opacity 0.1s, rotate 0.3s, translate 0.3s',
      transitionDelay: '0.1s',
    },
    '&:focus-visible': { outline: '2px solid var(--input-color)', outlineOffset: '2px' },
    '&:checked, &[aria-checked="true"]': {
      backgroundColor: 'var(--input-color)',
      _before: {
        opacity: '1',
        clipPath: 'polygon(20% 100%, 20% 80%, 50% 80%, 50% 0%, 70% 0%, 70% 100%)',
      },
    },
    '&:indeterminate': {
      backgroundColor: 'var(--input-color)',
      _before: {
        opacity: '1',
        rotate: '0deg',
        translate: '0 -35%',
        clipPath: 'polygon(20% 100%, 20% 80%, 50% 80%, 50% 80%, 80% 80%, 80% 100%)',
      },
    },
    _disabled: { opacity: '0.2', cursor: 'not-allowed' },
  },
  variants: {
    color: {
      neutral: { color: 'var(--colors-neutral-content)', '--input-color': 'var(--colors-neutral)' },
      primary: { color: 'var(--colors-primary-content)', '--input-color': 'var(--colors-primary)' },
      secondary: { color: 'var(--colors-secondary-content)', '--input-color': 'var(--colors-secondary)' },
      accent: { color: 'var(--colors-accent-content)', '--input-color': 'var(--colors-accent)' },
      info: { color: 'var(--colors-info-content)', '--input-color': 'var(--colors-info)' },
      success: { color: 'var(--colors-success-content)', '--input-color': 'var(--colors-success)' },
      warning: { color: 'var(--colors-warning-content)', '--input-color': 'var(--colors-warning)' },
      error: { color: 'var(--colors-error-content)', '--input-color': 'var(--colors-error)' },
    },
    size: {
      xs: { '--checkbox-size': '1rem', padding: '0.125rem' },
      sm: { '--checkbox-size': '1.25rem', padding: '0.1875rem' },
      md: { '--checkbox-size': '1.5rem', padding: '0.25rem' },
      lg: { '--checkbox-size': '1.75rem', padding: '0.3125rem' },
      xl: { '--checkbox-size': '2rem', padding: '0.375rem' },
    },
  },
})
