import { cva } from '../../styled-system/css'

export const fileInputStyles = cva({
  base: {
    display: 'inline-flex',
    alignItems: 'center',
    cursor: 'pointer',
    userSelect: 'none',
    width: 'clamp(3rem, 20rem, 100%)',
    height: '2.5rem',
    paddingInlineEnd: '0.75rem',
    fontSize: '0.875rem',
    lineHeight: '2',
    borderRadius: 'var(--radius-field)',
    backgroundColor: 'var(--colors-base-100)',
    '--input-color': 'color-mix(in oklab, var(--colors-base-content) 20%, transparent)',
    border: 'var(--border, 1px) solid var(--input-color)',
    boxShadow: '0 1px color-mix(in oklab, var(--input-color) 10%, transparent) inset, 0 -1px oklch(100% 0 0 / 0.1) inset',
    '&::file-selector-button': {
      marginInlineEnd: '1rem',
      cursor: 'pointer',
      userSelect: 'none',
      paddingInline: '1rem',
      height: 'calc(100% + var(--border, 1px) * 2)',
      marginBlock: 'calc(var(--border, 1px) * -1)',
      marginInlineStart: 'calc(var(--border, 1px) * -1)',
      fontSize: '0.875rem',
      fontWeight: '600',
      borderWidth: 'var(--border, 1px)',
      borderStyle: 'solid',
      borderColor: 'color-mix(in oklab, var(--colors-base-200), #000 5%)',
      borderStartStartRadius: 'calc(var(--radius-field) - var(--border, 1px))',
      borderEndStartRadius: 'calc(var(--radius-field) - var(--border, 1px))',
      borderStartEndRadius: '0',
      borderEndEndRadius: '0',
      color: 'var(--colors-base-content)',
      backgroundColor: 'var(--colors-base-200)',
    },
    _focus: {
      '--input-color': 'var(--colors-base-content)',
      boxShadow: '0 1px color-mix(in oklab, var(--input-color) 10%, transparent)',
      outline: '2px solid var(--input-color)',
      outlineOffset: '2px',
    },
    _disabled: {
      borderColor: 'var(--colors-base-200)',
      backgroundColor: 'var(--colors-base-200)',
      cursor: 'not-allowed',
      boxShadow: 'none',
      '&::file-selector-button': { cursor: 'not-allowed', backgroundColor: 'var(--colors-base-200)' },
    },
  },
  variants: {
    color: {
      neutral: { '&::file-selector-button': { backgroundColor: 'var(--colors-neutral)', color: 'var(--colors-neutral-content)' } },
      primary: { '&::file-selector-button': { backgroundColor: 'var(--colors-primary)', color: 'var(--colors-primary-content)' } },
      secondary: { '&::file-selector-button': { backgroundColor: 'var(--colors-secondary)', color: 'var(--colors-secondary-content)' } },
      accent: { '&::file-selector-button': { backgroundColor: 'var(--colors-accent)', color: 'var(--colors-accent-content)' } },
      info: { '&::file-selector-button': { backgroundColor: 'var(--colors-info)', color: 'var(--colors-info-content)' } },
      success: { '&::file-selector-button': { backgroundColor: 'var(--colors-success)', color: 'var(--colors-success-content)' } },
      warning: { '&::file-selector-button': { backgroundColor: 'var(--colors-warning)', color: 'var(--colors-warning-content)' } },
      error: { '&::file-selector-button': { backgroundColor: 'var(--colors-error)', color: 'var(--colors-error-content)' } },
    },
    size: {
      xs: { height: '1.5rem', fontSize: '0.6875rem', lineHeight: '1rem' },
      sm: { height: '2rem', fontSize: '0.75rem', lineHeight: '1.5rem' },
      md: { height: '2.5rem', fontSize: '0.875rem', lineHeight: '2' },
      lg: { height: '3rem', fontSize: '1.125rem', lineHeight: '2.5rem' },
      xl: { height: '3.5rem', fontSize: '1.125rem', lineHeight: '3rem', paddingInlineEnd: '1.5rem' },
    },
    ghost: {
      true: {
        backgroundColor: 'transparent',
        boxShadow: 'none',
        borderColor: 'transparent',
        '&::file-selector-button': { marginInlineStart: '0' },
      },
    },
  },
})
