import { cva } from '../../styled-system/css'

export const fileInputStyles = cva({
  base: {
    display: 'inline-flex',
    alignItems: 'center',
    cursor: 'pointer',
    userSelect: 'none',
    width: 'clamp(3rem, 20rem, 100%)',
    height: 'token(spacing.10)',
    paddingInlineEnd: 'token(spacing.3)',
    fontSize: 'token(fontSizes.md)',
    lineHeight: '2',
    borderRadius: 'var(--radius-field)',
    backgroundColor: 'token(colors.base-100)',
    '--input-color': 'color-mix(in oklab, token(colors.base-content) 20%, transparent)',
    border: 'var(--border, 1px) solid var(--input-color)',
    boxShadow: '0 1px color-mix(in oklab, var(--input-color) 10%, transparent) inset, 0 -1px oklch(100% 0 0 / 0.1) inset',
    '&::file-selector-button': {
      marginInlineEnd: 'token(spacing.4)',
      cursor: 'pointer',
      userSelect: 'none',
      paddingInline: 'token(spacing.4)',
      height: 'calc(100% + var(--border, 1px) * 2)',
      marginBlock: 'calc(var(--border, 1px) * -1)',
      marginInlineStart: 'calc(var(--border, 1px) * -1)',
      fontSize: 'token(fontSizes.md)',
      fontWeight: '600',
      borderWidth: 'var(--border, 1px)',
      borderStyle: 'solid',
      borderColor: 'color-mix(in oklab, token(colors.base-200), #000 5%)',
      borderStartStartRadius: 'calc(var(--radius-field) - var(--border, 1px))',
      borderEndStartRadius: 'calc(var(--radius-field) - var(--border, 1px))',
      borderStartEndRadius: '0',
      borderEndEndRadius: '0',
      color: 'token(colors.base-content)',
      backgroundColor: 'token(colors.base-200)',
    },
    _focus: {
      '--input-color': 'token(colors.base-content)',
      boxShadow: '0 1px color-mix(in oklab, var(--input-color) 10%, transparent)',
      outline: '2px solid var(--input-color)',
      outlineOffset: '2px',
    },
    _disabled: {
      borderColor: 'token(colors.base-200)',
      backgroundColor: 'token(colors.base-200)',
      cursor: 'not-allowed',
      boxShadow: 'none',
      '&::file-selector-button': { cursor: 'not-allowed', backgroundColor: 'token(colors.base-200)' },
    },
  },
  variants: {
    color: {
      neutral: { '&::file-selector-button': { backgroundColor: 'token(colors.neutral)', color: 'token(colors.neutral-content)' } },
      primary: { '&::file-selector-button': { backgroundColor: 'token(colors.primary)', color: 'token(colors.primary-content)' } },
      secondary: { '&::file-selector-button': { backgroundColor: 'token(colors.secondary)', color: 'token(colors.secondary-content)' } },
      accent: { '&::file-selector-button': { backgroundColor: 'token(colors.accent)', color: 'token(colors.accent-content)' } },
      info: { '&::file-selector-button': { backgroundColor: 'token(colors.info)', color: 'token(colors.info-content)' } },
      success: { '&::file-selector-button': { backgroundColor: 'token(colors.success)', color: 'token(colors.success-content)' } },
      warning: { '&::file-selector-button': { backgroundColor: 'token(colors.warning)', color: 'token(colors.warning-content)' } },
      error: { '&::file-selector-button': { backgroundColor: 'token(colors.error)', color: 'token(colors.error-content)' } },
    },
    size: {
      xs: { height: 'token(spacing.6)', fontSize: 'token(fontSizes.xs)', lineHeight: 'token(spacing.4)' },
      sm: { height: 'token(spacing.8)', fontSize: 'token(fontSizes.sm)', lineHeight: 'token(spacing.6)' },
      md: { height: 'token(spacing.10)', fontSize: 'token(fontSizes.md)', lineHeight: '2' },
      lg: { height: 'token(spacing.12)', fontSize: 'token(fontSizes.xl)', lineHeight: 'token(spacing.10)' },
      xl: { height: 'token(spacing.14)', fontSize: 'token(fontSizes.xl)', lineHeight: 'token(spacing.12)', paddingInlineEnd: 'token(spacing.6)' },
    },
    ghost: {
      true: {
        backgroundColor: 'transparent',
        boxShadow: 'none',
        borderColor: 'transparent',
        '&::file-selector-button': { marginInlineStart: '0' },
      },
    },
  },
  defaultVariants: {
    size: 'md',
  },
})
