import { defineRecipe } from '@pandacss/dev'

export const selectRecipe = defineRecipe({
  className:'select',
  base: {
    display: 'inline-flex',
    alignItems: 'center',
    gap: 'token(spacing.1.5)',
    width: 'clamp(3rem, 20rem, 100%)',
    height: 'token(spacing.10)',
    paddingInlineStart: 'token(spacing.3)',
    paddingInlineEnd: 'token(spacing.7)',
    fontSize: 'token(fontSizes.md)',
    borderRadius: 'var(--radius-field)',
    backgroundColor: 'base-100',
    whiteSpace: 'nowrap',
    overflow: 'hidden',
    textOverflow: 'ellipsis',
    cursor: 'pointer',
    appearance: 'none',
    '--input-color': 'color-mix(in oklab, token(colors.base-content) 20%, transparent)',
    border: 'var(--border, 1px) solid var(--input-color)',
    boxShadow: '0 1px color-mix(in oklab, var(--input-color) 10%, transparent) inset, 0 -1px oklch(100% 0 0 / 0.1) inset',
    backgroundImage: 'linear-gradient(45deg, transparent 50%, currentColor 50%), linear-gradient(135deg, currentColor 50%, transparent 50%)',
    backgroundPosition: 'calc(100% - 20px) calc(1px + 50%), calc(100% - 16.1px) calc(1px + 50%)',
    backgroundSize: '4px 4px, 4px 4px',
    backgroundRepeat: 'no-repeat',
    _disabled: {
      borderColor: 'base-200',
      backgroundColor: 'base-200',
      color: 'color-mix(in oklab, token(colors.base-content) 40%, transparent)',
      cursor: 'not-allowed',
      boxShadow: 'none',
    },
    _focus: {
      '--input-color': 'token(colors.base-content)',
      boxShadow: '0 1px color-mix(in oklab, var(--input-color) 10%, transparent)',
      outline: '2px solid var(--input-color)',
      outlineOffset: '2px',
      backgroundImage: 'linear-gradient(135deg, transparent 50%, currentColor 50%), linear-gradient(45deg, currentColor 50%, transparent 50%)',
    },
  },
  variants: {
    color: {
      neutral: { _focus: { '--input-color': 'token(colors.neutral)' } },
      primary: { _focus: { '--input-color': 'token(colors.primary)' } },
      secondary: { _focus: { '--input-color': 'token(colors.secondary)' } },
      accent: { _focus: { '--input-color': 'token(colors.accent)' } },
      info: { _focus: { '--input-color': 'token(colors.info)' } },
      success: { _focus: { '--input-color': 'token(colors.success)' } },
      warning: { _focus: { '--input-color': 'token(colors.warning)' } },
      error: { _focus: { '--input-color': 'token(colors.error)' } },
    },
    size: {
      xs: { height: 'token(spacing.6)', fontSize: 'token(fontSizes.xs)' },
      sm: { height: 'token(spacing.8)', fontSize: 'token(fontSizes.sm)' },
      md: { height: 'token(spacing.10)', fontSize: 'token(fontSizes.md)' },
      lg: { height: 'token(spacing.12)', fontSize: 'token(fontSizes.xl)' },
      xl: { height: 'token(spacing.14)', fontSize: 'token(fontSizes.3xl)' },
    },
    ghost: {
      true: { backgroundColor: 'transparent', boxShadow: 'none', borderColor: 'transparent' },
    },
  },
  defaultVariants: {
    size: 'md',
  },
})
