import { cva } from '../../styled-system/css'

export const selectStyles = cva({
  base: {
    display: 'inline-flex',
    alignItems: 'center',
    gap: '0.375rem',
    width: 'clamp(3rem, 20rem, 100%)',
    height: '2.5rem',
    paddingInlineStart: '0.75rem',
    paddingInlineEnd: '1.75rem',
    fontSize: '0.875rem',
    borderRadius: 'var(--radius-field)',
    backgroundColor: 'var(--colors-base-100)',
    whiteSpace: 'nowrap',
    overflow: 'hidden',
    textOverflow: 'ellipsis',
    cursor: 'pointer',
    appearance: 'none',
    '--input-color': 'color-mix(in oklab, var(--colors-base-content) 20%, transparent)',
    border: 'var(--border, 1px) solid var(--input-color)',
    boxShadow: '0 1px color-mix(in oklab, var(--input-color) 10%, transparent) inset, 0 -1px oklch(100% 0 0 / 0.1) inset',
    backgroundImage: 'linear-gradient(45deg, transparent 50%, currentColor 50%), linear-gradient(135deg, currentColor 50%, transparent 50%)',
    backgroundPosition: 'calc(100% - 20px) calc(1px + 50%), calc(100% - 16.1px) calc(1px + 50%)',
    backgroundSize: '4px 4px, 4px 4px',
    backgroundRepeat: 'no-repeat',
    _disabled: {
      borderColor: 'var(--colors-base-200)',
      backgroundColor: 'var(--colors-base-200)',
      color: 'color-mix(in oklab, var(--colors-base-content) 40%, transparent)',
      cursor: 'not-allowed',
      boxShadow: 'none',
    },
    _focus: {
      '--input-color': 'var(--colors-base-content)',
      boxShadow: '0 1px color-mix(in oklab, var(--input-color) 10%, transparent)',
      outline: '2px solid var(--input-color)',
      outlineOffset: '2px',
      backgroundImage: 'linear-gradient(135deg, transparent 50%, currentColor 50%), linear-gradient(45deg, currentColor 50%, transparent 50%)',
    },
  },
  variants: {
    color: {
      neutral: { _focus: { '--input-color': 'var(--colors-neutral)' } },
      primary: { _focus: { '--input-color': 'var(--colors-primary)' } },
      secondary: { _focus: { '--input-color': 'var(--colors-secondary)' } },
      accent: { _focus: { '--input-color': 'var(--colors-accent)' } },
      info: { _focus: { '--input-color': 'var(--colors-info)' } },
      success: { _focus: { '--input-color': 'var(--colors-success)' } },
      warning: { _focus: { '--input-color': 'var(--colors-warning)' } },
      error: { _focus: { '--input-color': 'var(--colors-error)' } },
    },
    size: {
      xs: { height: '1.5rem', fontSize: '0.6875rem' },
      sm: { height: '2rem', fontSize: '0.75rem' },
      md: { height: '2.5rem', fontSize: '0.875rem' },
      lg: { height: '3rem', fontSize: '1.125rem' },
      xl: { height: '3.5rem', fontSize: '1.375rem' },
    },
    ghost: {
      true: { backgroundColor: 'transparent', boxShadow: 'none', borderColor: 'transparent' },
    },
  },
})
