/**
 * Build script for the npm library package.
 * Usage: bun run scripts/build-lib.ts
 *
 * Outputs:
 * - dist/index.js (ES module, mithril external)
 * - dist/index.d.ts (type declarations, generated by tsc)
 */

import { existsSync, rmSync, mkdirSync } from 'fs'
import { resolve } from 'path'

const ROOT = resolve(import.meta.dir, '..')
const OUTDIR = resolve(ROOT, 'dist')

// Clean output directory
if (existsSync(OUTDIR)) {
  rmSync(OUTDIR, { recursive: true })
}
mkdirSync(OUTDIR, { recursive: true })

console.log('Building library → dist/')

// Step 1: Bundle JS with Bun
const result = await Bun.build({
  entrypoints: [resolve(ROOT, 'src/index.js')],
  outdir: OUTDIR,
  format: 'esm',
  minify: true,
  splitting: true,
  external: ['mithril'],
  naming: {
    entry: '[name].[ext]',
    chunk: '[name]-[hash].[ext]',
    asset: '[name]-[hash].[ext]',
  },
})

if (!result.success) {
  console.error('Build failed:')
  for (const message of result.logs) {
    console.error(message)
  }
  process.exit(1)
}

console.log('JS bundle built successfully')

// Step 2: Generate type declarations with tsc
console.log('Generating type declarations...')
const tsc = Bun.spawnSync(['bunx', 'tsc', '--noEmit', '--project', 'tsconfig.lib.json'], {
  cwd: ROOT,
  stdio: ['inherit', 'inherit', 'inherit'],
})

if (tsc.exitCode !== 0) {
  console.error('TypeScript declaration generation failed')
  process.exit(1)
}

console.log('Type declarations generated')
console.log(`\nBuild succeeded. Output in ${OUTDIR}`)

// List output files
import { readdirSync, statSync } from 'fs'
function listFiles(dir: string, prefix = '') {
  for (const entry of readdirSync(dir)) {
    const path = `${prefix}${entry}`
    const fullPath = `${dir}/${entry}`
    if (statSync(fullPath).isDirectory()) {
      console.log(`  📁 ${path}/`)
      listFiles(fullPath, `${path}/`)
    } else {
      const size = statSync(fullPath).size
      console.log(`  📄 ${path} (${(size / 1024).toFixed(1)} KB)`)
    }
  }
}
console.log('\nOutput files:')
listFiles(OUTDIR)
