#!/usr/bin/env bun
/**
 * Checks the PUBLISHED declarations (`src/**`) with `skipLibCheck` OFF — the
 * default a consumer actually gets.
 *
 * Why it exists: every other project here runs with `skipLibCheck: true`,
 * because `styled-system/` (generated by Panda) and `@pandacss/types` ship
 * errors of their own — e.g. `styled-system/jsx/index.d.ts` re-exports a
 * `./factory` module that Panda 1.12 does not generate. `skipLibCheck` cannot
 * tell "our" declarations from third-party ones, so a REAL error in our own
 * `.d.ts` — `ListAttrs<T> extends ComponentAttrs` with an incompatible `key`
 * was one — stays invisible in those projects.
 *
 * So: compile everything, then fail only on errors located under `src/`, and
 * say how many were ignored elsewhere so the blind spot is never silent.
 */
import { spawnSync } from 'node:child_process'
import { join } from 'node:path'

const ROOT = join(import.meta.dir, '..')

const tsc = spawnSync(
  join(ROOT, 'node_modules', '.bin', 'tsc'),
  ['--noEmit', '--project', 'tsconfig.dts.json'],
  { cwd: ROOT, encoding: 'utf8' },
)

const output = `${tsc.stdout ?? ''}${tsc.stderr ?? ''}`
const errors = output
  .split('\n')
  .map((line) => line.trim())
  .filter((line) => /error TS\d+/.test(line))

const ours = errors.filter((line) => line.startsWith('src/'))
const foreign = errors.length - ours.length

if (ours.length > 0) {
  console.error(`✖ ${ours.length} error(es) en los tipos que publicamos (src/**):\n`)
  for (const line of ours) console.error(`  ${line}`)
  console.error('\n  Se comprueban con skipLibCheck off, como los ve un consumidor.')
  if (foreign > 0) console.error(`  (${foreign} error(es) en tipos generados o de terceros, ignorados)`)
  process.exit(1)
}

console.log('✔ src/**: 0 errores en los tipos publicados (skipLibCheck off)')
if (foreign > 0) {
  console.log(`  ${foreign} error(es) ignorados en tipos generados o de terceros (styled-system/, @pandacss/types)`)
}
