/**
 * Counts the components in src/components.
 *
 * Rule: one folder = one component. Subcomponents (e.g. <MenuItem> inside
 * <Menu>, <CardBody> inside <Card>) do NOT count — they live in the same
 * folder as their parent component.
 *
 * Usage:
 *   bun run count          # prints just the number, e.g. "70"
 *
 * The run also regenerates playground/pages/landing/components-count.js, the
 * module the landing page imports to display the count, so the page can never
 * drift from the real number of folders.
 *
 * Also exports countComponents() so other scripts can reuse the same rule.
 */
import { readdirSync, writeFileSync, mkdirSync } from 'fs'
import { resolve } from 'path'

const ROOT = resolve(import.meta.dir, '..')
const COMPONENTS_DIR = resolve(ROOT, 'src', 'components')
const LANDING_COUNT_MODULE = resolve(ROOT, 'playground', 'pages', 'landing', 'components-count.js')

/** Number of component folders in src/components (directories only). */
export function countComponents(dir = COMPONENTS_DIR): number {
  return readdirSync(dir, { withFileTypes: true })
    .filter((entry) => entry.isDirectory())
    .length
}

/** Regenerates the module the landing page imports to display the count. */
export function writeCountModule(count: number, target = LANDING_COUNT_MODULE): void {
  mkdirSync(resolve(target, '..'), { recursive: true })
  writeFileSync(
    target,
    `// Auto-generated by scripts/count-components.ts — do not edit manually.
// Run \`bun run count\` to refresh it after adding or removing a component.
export const COMPONENTS_COUNT = ${count}
`,
  )
}

// `import.meta.main` is true only when this file is run directly
// (bun run count), not when it is imported by another module.
if (import.meta.main) {
  const count = countComponents()
  writeCountModule(count)
  console.log(count)
}
